### ISSUE TITLE
when dsn use https will throw SentryError: HTTP Error (400): No JSON data was found

### ISSUE THREAD

**Issue by qinyang912** [getsentry/sentry-electron#124]
```
{ SentryError: HTTP Error (400): No JSON data was found
    at new SentryError (/Volumes/west/rishiqing/rishiqing-electron/node_modules/@sentry/core/src/error.ts:7:5)
    at ClientRequest.req.on (/Volumes/west/rishiqing/rishiqing-electron/node_modules/@sentry/electron/src/main/transports/net.ts:39:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7) name: 'SentryError' }
```

**Comment by timfish** [comment]
I think that's a response from the sentry server. If you're hosting your own server [it might need updating](https://github.com/getsentry/sentry/issues/5716).

**Comment by jan-auer** [comment]
@HazAT This is a bug in the base transport, we should use the DSN's protocol and pass it to the protocol option for transports. 

@qinyang912 As a workaround, you can enable HTTP for the `/api/x/store/` endpoint.
