### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by joeyer** [getsentry/sentry-electron#138]
$ node sentry-symbols.js

error
  ...options,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by timfish** [comment]
What version of node are you using? I guess you're using a version which doesn't support the spread syntax.

**Comment by joeyer** [comment]
node:8.2.1   electron:1.8.4

**Comment by timfish** [comment]
The node version you are quoting here is suspiciously the one shipped with v1.8.4 of Electron. I'm asking which version of node you have installed on your system. You can get this by running:
```
node -v
```

**Comment by joeyer** [comment]
node:8.2.1

**Comment by joeyer** [comment]
What is the minimum supported version of node?

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
