### ISSUE TITLE
tslib_1__default is not defined

### ISSUE THREAD

**Issue by Galkon** [getsentry/sentry-electron#158]
I am getting this as of updating to the latest `@sentry/electron` version `^0.15.0`, it occurs when an exception or warning is thrown or reported, I believe. I found similar Issues reported in `@sentry/browser`, and I believe this is due to `@sentry/electron` is not using the latest version of `@sentry/browser` which is `^4.6.3`, instead it uses `^4.5.0`.

```
uncaughtException: tslib_1__default is not defined
ReferenceError: tslib_1__default is not defined
    at decycle (/node_modules/@sentry/electron/node_modules/@sentry/utils/object.js:283:86)
    at Object.<anonymous> (/node_modules/@sentry/electron/node_modules/@sentry/utils/object.js:312:102)
    at JSON.stringify (<anonymous>)
    at serialize (/node_modules/@sentry/electron/node_modules/@sentry/utils/object.js:15:17)
    at GlobalHandlers.eventFromGlobalHandler (/node_modules/@sentry/electron/node_modules/@sentry/browser/src/integrations/globalhandlers.ts:117:23)
    at Array.<anonymous> (/node_modules/@sentry/electron/node_modules/@sentry/browser/src/integrations/globalhandlers.ts:68:43)
    at notifyHandlers (/node_modules/@sentry/electron/node_modules/@sentry/browser/src/tracekit.ts:322:22)
    at traceKitWindowOnUnhandledRejection (/node_modules/@sentry/electron/node_modules/@sentry/browser/src/tracekit.ts:418:5)
```

**Comment by HazAT** [comment]
Thanks, `0.16.0` is on it's way fixing this.
