### ISSUE TITLE
Not compatible with webpack bundled main process js 

### ISSUE THREAD

**Issue by oHaiyang** [getsentry/sentry-electron#179]
We use webpack to bundle main process js files, the [target](https://webpack.js.org/configuration/target/) is set to `electron-main`.

The aplication throws after start:

```
TypeError: mod.require is not a function
    at Object.dynamicRequire (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:12699:16)
    at Object.specificInit (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:11068:41)
    at Object.init (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:11417:16)
    at Object.<anonymous> (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:186522:8)
    at Object../src/main-process/init/setupSentry.js (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:186525:30)
    at __webpack_require__ (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:20:30)
    at Object../src/main-process/init/index.js (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:186451:1)
    at __webpack_require__ (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:20:30)
    at Object.<anonymous> (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:187934:1)
    at Object../src/main.js (/home/haiyang/Coding/dichat-phoenix/packages/client/bundle/main/index.js:188160:30)
```

**Comment by HazAT** [comment]
Can you try this: 
https://github.com/getsentry/sentry-electron/issues/92#issuecomment-453534680

**Comment by oHaiyang** [comment]
Okay, problem solved, thanks!
