### ISSUE TITLE
App crashes using Sentry/electron 2.0.0 + Electron 10.0.0

### ISSUE THREAD

**Issue by theArina** [getsentry/sentry-electron#264]
#  Versions + Platform

- [ ] SDK version - `@sentry/electron@v2.0.0`
- [ ] Electron version - `electron@v10.0.0`
- [ ] Platform - `Windows`

## Description

I was using Electron 9 and sentry/electron 1.3.0, then I upgraded Electron to 10, worked fine, but then I tried to upgrade sentry to version 2 and now the app crashes every time with the log below.
It also continues to happen when I remove sentry/electron. Crash disappears only when I reverse all changes in repository. 
I've already tried to remove all node modules, remove sentry from dependencies and rerun npm i. 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'electron',
1 verbose cli   '--scripts-prepend-node-path=auto'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
```
...
```
10 silly lifecycle app@0.0.28~electron: Args: [ '/d /s /c', 'electron --noDevServer . --disable-d3d11' ]
11 silly lifecycle app@0.0.28~electron: Returned: code: 4294930435  signal: null
12 info lifecycle app@0.0.28~electron: Failed to exec electron script
13 verbose stack Error: app@0.0.28 electron: `electron --noDevServer . --disable-d3d11`
13 verbose stack Exit status 4294930435
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose stack     at Process.callbackTrampoline (internal/async_hooks.js:120:14)
14 verbose pkgid app@0.0.28
```
...
```
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "electron" "--scripts-prepend-node-path=auto"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 4294930435
22 error app@0.0.28 electron: `electron --noDevServer . --disable-d3d11`
22 error Exit status 4294930435
23 error Failed at the app@0.0.28 electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294930435, true ]
`

**Comment by james-criscuolo** [comment]
This issue still exists in 2.0.4.

**Comment by timfish** [comment]
> also continues to happen when I remove sentry/electron

This suggests that this issue is not caused by `@sentry/electron`. Please reopen with a reproduction example if you can still reproduce this.
