### ISSUE TITLE
init() crashes in preload script

### ISSUE THREAD

**Issue by Achder** [getsentry/sentry-electron#351]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.5.1`
- [x] Electron version - `electron@v13.1.6`
- [x] Platform - `Windows`

## Description

I'm currently updating my app to use electron 13 and trying to apply proper context isolation and disabling node integration.

```
webPreferences: {
	webSecurity: isDevelopment ? false : true,
	nodeIntegration: false,
	contextIsolation: true,
	worldSafeExecuteJavaScript: true,
	spellcheck: false,
	preload: path.resolve(path.join(app.getAppPath(), 'preload.js')),
	defaultFontSize: 14,
}
```

I know from other issues postet here, that I need to call init() in the main process, my preload script and the isolated renderer.
But my preload script crashes with the following error:

```
VM75 renderer_init.js:93 TypeError: Cannot read property 'getAppPath' of undefined
    at eval (webpack://***/./node_modules/@sentry/electron/esm/main/normalize.js?:10:58)
    at Module../node_modules/@sentry/electron/esm/main/normalize.js (C:\Development\***\dist\main\preload.js:355:1)
    at __webpack_require__ (C:\Development\***\dist\main\preload.js:5085:33)
    at fn (C:\Development\***\dist\main\preload.js:5244:21)
    at eval (webpack://***/./node_modules/@sentry/electron/esm/main/backend.js?:25:69)
    at Module../node_modules/@sentry/electron/esm/main/backend.js (C:\Development\***\dist\main\preload.js:278:1)
    at __webpack_require__ (C:\Development\***\dist\main\preload.js:5085:33)
    at fn (C:\Development\***\dist\main\preload.js:5244:21)
    at eval (webpack://***/./node_modules/@sentry/electron/esm/main/client.js?:9:66)
    at Module../node_modules/@sentry/electron/esm/main/client.js (C:\Development\***\dist\main\preload.js:289:1)
```

getAppPath() is only available in the main process.

I'm using webpack as a bundler and selected `electron-preload` as my target for the preload script:
```
merge(common, {
	mode: 'development',
	target: 'electron-preload',
	entry: 'common/preload.ts',
	output: {
		filename: 'preload.js',
		chunkFilename: '[name].bundle.js',
		path: path.resolve(__dirname, 'dist/main'),
		globalObject: 'global',
	},
})
```

In my preload script I simply call:
```
import { init } from '@sentry/electron'
import { config } from './sentry'
init(config)
```

**Comment by timfish** [comment]
For the preload you need to use `electron-renderer` webpack target. 

This issue is caused by how webpack selects which files to bundle depending on the target.
