### ISSUE TITLE
Errors reading or writing breadcrumbs

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#38]
```
Error: UNKNOWN: unknown error, open 'C:\Users\Username\AppData\Local\AppName\sentry\crumbs.json'
  File "fs.js", line 558, col 18, in Object.fs.openSync
  File "ELECTRON_ASAR.js", line 173, col 20, in Object.module.(anonymous function) [as openSync]
  File "fs.js", line 1233, col 33, in Object.fs.writeFileSync
  File "node_modules/@sentry/electron/dist/lib/store.js", line 85, col 14, in Store.flush
  File "node_modules/@sentry/electron/dist/lib/store.js", line 52, col 37, in Immediate.setImmediate
  File "timers.js", line 651, col 20, in runCallback
  File "timers.js", line 624, col 5, in tryOnImmediate
  File "timers.js", line 596, col 5, in processImmediate [as _immediateCallback]
```
```
{
  code: UNKNOWN, 
  errno: -4094, 
  path: C:\Users\Username\AppData\Local\AppName\sentry\crumbs.json, 
  syscall: open
}
```

**Comment by timfish** [comment]
This one appears to be because `breadcrumbs.json` is an empty file
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Store.get (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\utils\dist\lib\store.js:54:24)
    at ElectronBackend.<anonymous> (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\electron\dist\lib\backend.js:145:37)
    at Generator.next (<anonymous>)
    at C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\electron\dist\lib\backend.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\electron\dist\lib\backend.js:3:12)
    at ElectronBackend.loadBreadcrumbs (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\electron\dist\lib\backend.js:144:16)
    at ElectronFrontend.<anonymous> (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:335:64)
    at step (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:40:23)
    at Object.next (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:21:53)
    at C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:15:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:11:12)
    at ElectronFrontend.FrontendBase.getBreadcrumbs (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:328:16)
    at ElectronFrontend.<anonymous> (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:217:51)
    at step (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:40:23)
    at Object.next (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:21:53)
    at C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:15:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:11:12)
    at ElectronFrontend.FrontendBase.addBreadcrumb (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\core\dist\lib\base.js:196:16)
    at App.emitter.emit.args [as emit] (C:\Users\tim\Documents\Repos\MyApp\node_modules\@sentry\electron\dist\lib\backend.js:319:46)
```

**Comment by jan-auer** [comment]
We should generally handle all errors when reading/writing any state (i.e. breadcrumbs, context and queues) and recover as gracefully as possible.

**Comment by jan-auer** [comment]
Should be fixed with the latest release.
