### ISSUE TITLE
3.0.0 Webpack "Self-reference dependency has unused export name: This should not happen"

### ISSUE THREAD

**Issue by adambailey-** [getsentry/sentry-electron#416]
Hi there! I'm really excited to see the 3.0 release bringing release health metrics, thanks for adding that. 

This morning I attempted to migrate to version 3.0 using https://github.com/getsentry/sentry-electron/blob/3.0.0/MIGRATION.md#. It all works, but when using Webpack to make a production build `mode: 'production'` of my app, I receive the following errors:

```
ERROR in ./node_modules/@sentry/electron/preload/index.js
Self-reference dependency has unused export name: This should not happen
Error: Self-reference dependency has unused export name: This should not happen
    at CommonJsSelfReferenceDependencyTemplate.apply (/Users/vagrant/git/node_modules/webpack/lib/dependencies/CommonJsSelfReferenceDependency.js:102:10)
    at JavascriptGenerator.sourceDependency (/Users/vagrant/git/node_modules/webpack/lib/javascript/JavascriptGenerator.js:206:12)
    at JavascriptGenerator.sourceModule (/Users/vagrant/git/node_modules/webpack/lib/javascript/JavascriptGenerator.js:112:9)
    at JavascriptGenerator.generate (/Users/vagrant/git/node_modules/webpack/lib/javascript/JavascriptGenerator.js:98:8)
    at NormalModule.codeGeneration (/Users/vagrant/git/node_modules/webpack/lib/NormalModule.js:1198:22)
    at /Users/vagrant/git/node_modules/webpack/lib/Compilation.js:3324:22
    at /Users/vagrant/git/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/Users/vagrant/git/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/Users/vagrant/git/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/Users/vagrant/git/node_modules/webpack/lib/CacheFacade.js:111:15)
 @ ./node_modules/@sentry/electron/main/integrations/preload-injection.js 40:18-59
 @ ./node_modules/@sentry/electron/main/integrations/index.js 13:26-56
 @ ./node_modules/@sentry/electron/main/index.js 6:33-58
 @ ./src/app/crash-reporter/crash-reporter.js 281:85-117
 @ ./src/js/index.tsx 15:0-76 31:2-25

ERROR in ./node_modules/@sentry/electron/preload/legacy.js
Self-reference dependency has unused export name: This should not happen
Error: Self-reference dependency has unused export name: This should not happen
    at CommonJsSelfReferenceDependencyTemplate.apply (/Users/vagrant/git/node_modules/webpack/lib/dependencies/CommonJsSelfReferenceDependency.js:102:10)
    at JavascriptGenerator.sourceDependency (/Users/vagrant/git/node_modules/webpack/lib/javascript/JavascriptGenerator.js:206:12)
    at JavascriptGenerator.sourceModule (/Users/vagrant/git/node_modules/webpack/lib/javascript/JavascriptGenerator.js:112:9)
    at JavascriptGenerator.generate (/Users/vagrant/git/node_modules/webpack/lib/javascript/JavascriptGenerator.js:98:8)
    at NormalModule.codeGeneration (/Users/vagrant/git/node_modules/webpack/lib/NormalModule.js:1198:22)
    at /Users/vagrant/git/node_modules/webpack/lib/Compilation.js:3324:22
    at /Users/vagrant/git/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/Users/vagrant/git/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/Users/vagrant/git/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/Users/vagrant/git/node_modules/webpack/lib/CacheFacade.js:111:15)
 @ ./node_modules/@sentry/electron/main/integrations/preload-injection.js 39:18-60
 @ ./node_modules/@sentry/electron/main/integrations/index.js 13:26-56
 @ ./node_modules/@sentry/electron/main/index.js 6:33-58
 @ ./src/app/crash-reporter/crash-reporter.js 281:85-117
 @ ./src/js/index.tsx 15:0-76 31:2-25
```

My crash reporter code is mostly unchanged from 2.x implementation (I was using 2.5.4 before). I have a single `crash-reporter.js` file that the renderer and main process share. Here is the basic structure of that file:

```
module.exports.initializeCrashReporter = function () {
    Sentry().init({
      dsn: '__DSN__',
      release: '__VERSION__'
    });
};

// This has to be dynamically loaded because it's different between the main and renderer processes
// https://github.com/getsentry/sentry-electron/blob/3.0.0/MIGRATION.md#relative-imports
function Sentry() {
  return isRendererProcess()
    ? require('@sentry/electron/renderer')
    : require('@sentry/electron/main');
}
```

The only change I had to make to migrate to 3.x implementation was within the `Sentry` function, changing the require paths. Before, on `2.5.4`, the code was `return isRendererProcess()
    ? require('@sentry/electron/dist/renderer')
    : require('@sentry/electron/dist/main');`
Note that the `dist` has been removed from the path for 3.x impl.

Any advice here on how to fix this? I should note that development Webpack builds work completely fine, but changing my webpack config to `mode: 'production'` causes the error.

**Comment by timfish** [comment]
Is the compilation coming from the renderer process webpack build or the main process?

```
ERROR in ./node_modules/@sentry/electron/preload/index.js
```
This suggests that the preload is being picked up somewhere. Do you have a custom preload?

```
function Sentry() {
  return isRendererProcess()
    ? require('@sentry/electron/renderer')
    : require('@sentry/electron/main');
}
```
I would try and avoid this completely and NOT have a single `sentry.js` because a bundler will always try and pick up both entry points.

Instead have a seperate `init` for main and renderer. In the renderer, you can generally get away with an empty `init()` because most of the config is via the main.

**Comment by adambailey-** [comment]
Thanks, refactoring the code helps me work around the issue. Appreciate your time!

**Comment by quanglam2807** [comment]
I'm facing the same problem without knowing how to fix it. It worked with webpack 3 and then broke with webpack 5. It only fails when building the main process code with webpack :(

```js
# main
const Sentry = require('@sentry/electron/main');

Sentry.init({
  dsn: process.env.ELECTRON_APP_SENTRY_DSN,
  release: app.getVersion(),
  autoSessionTracking: false,
  // disable native crash reporting
  // as it mostly reports Electron's bugs (upstream bugs)
  integrations: (defaultIntegrations) => defaultIntegrations
    .filter((i) => i.name !== Sentry.Integrations.SentryMinidump.Id),
});
```

**Comment by quanglam2807** [comment]
Here's the error:

```
ERROR in ./node_modules/@sentry/electron/preload/index.js
Self-reference dependency has unused export name: This should not happen
Error: Self-reference dependency has unused export name: This should not happen
    at CommonJsSelfReferenceDependencyTemplate.apply (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/dependencies/CommonJsSelfReferenceDependency.js:102:10)
    at JavascriptGenerator.sourceDependency (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/javascript/JavascriptGenerator.js:206:12)
    at JavascriptGenerator.sourceModule (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/javascript/JavascriptGenerator.js:112:9)
    at JavascriptGenerator.generate (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/javascript/JavascriptGenerator.js:98:8)
    at NormalModule.codeGeneration (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/NormalModule.js:1203:22)
    at /Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3325:22
    at /Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/CacheFacade.js:111:15)
    at Compilation._codeGenerationModule (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3318:9)
    at /Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3225:11
    at arrayIterator (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/neo-async/async.js:3467:9)
    at done (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/neo-async/async.js:3527:9)
    at /Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3239:8
    at /Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3349:5
 @ ./node_modules/@sentry/electron/main/integrations/preload-injection.js 40:18-59
 @ ./node_modules/@sentry/electron/main/integrations/index.js 13:26-56
 @ ./node_modules/@sentry/electron/main/index.js 7:59-84
 @ ./main-src/electron.js 20:4-36

ERROR in ./node_modules/@sentry/electron/preload/legacy.js
Self-reference dependency has unused export name: This should not happen
Error: Self-reference dependency has unused export name: This should not happen
    at CommonJsSelfReferenceDependencyTemplate.apply (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/dependencies/CommonJsSelfReferenceDependency.js:102:10)
    at JavascriptGenerator.sourceDependency (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/javascript/JavascriptGenerator.js:206:12)
    at JavascriptGenerator.sourceModule (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/javascript/JavascriptGenerator.js:112:9)
    at JavascriptGenerator.generate (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/javascript/JavascriptGenerator.js:98:8)
    at NormalModule.codeGeneration (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/NormalModule.js:1203:22)
    at /Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3325:22
    at /Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/CacheFacade.js:111:15)
    at Compilation._codeGenerationModule (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3318:9)
    at /Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3225:11
    at arrayIterator (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/neo-async/async.js:3467:9)
    at timesSync (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/neo-async/async.js:3463:5)
    at runIteration (/Users/quanglam2807/Documents/GitHub/webcatalog/webcatalog-cloud/node_modules/webpack/lib/Compilation.js:3205:13)
 @ ./node_modules/@sentry/electron/main/integrations/preload-injection.js 39:18-60
 @ ./node_modules/@sentry/electron/main/integrations/index.js 13:26-56
 @ ./node_modules/@sentry/electron/main/index.js 7:59-84
 @ ./main-src/electron.js 20:4-36
```

**Comment by quanglam2807** [comment]
Adding
```js
    optimization: {
      sideEffects: false,
    },
```

fixes the problem but I don't know why.

**Comment by timfish** [comment]
@quanglam2807 probably best to open a new issue with as much detail as possible of how to reproduce your issue.

**Comment by quanglam2807** [comment]
Thank you, @timfish! This PR fixes the issue: https://github.com/getsentry/sentry-electron/pull/446
