### ISSUE TITLE
TypeError: mod.require is not a function. Cannot upgrade to Sentry 3

### ISSUE THREAD

**Issue by zhex900** [getsentry/sentry-electron#422]
## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.2`
- [x] Electron version - `electron@v17.1.0`
- [x] Platform - `macOS`

## Description

I am trying to upgrade Sentry to the latest version. But I run into this problem. 

You can reproduce it with the following steps:
* ` npx create-electron-app my-new-app --template=typescript-webpack`
* `npm install @sentry/electron`
* `sentry-wizard --integration electron`
* In the main process, `src/index.ts`. I added this
```
import * as Sentry from "@sentry/electron";

Sentry.init({
  dsn: 'https://____.ingest.sentry.io/___',
});
````

````
⠹ Compiling Renderer CodeApp threw an error during load
TypeError: mod.require is not a function
    at dynamicRequire (/Users/jakehe/Code/my-new-app/.webpack/main/index.js:9186:16)
    at getIntegrations (/Users/jakehe/Code/my-new-app/.webpack/main/index.js:5269:70)
    at Object../node_modules/@sentry/electron/index.js (/Users/jakehe/Code/my-new-app/.webpack/main/index.js:5198:59)
    at __webpack_require__ (/Users/jakehe/Code/my-new-app/.webpack/main/index.js:12490:42)
    at Object../src/index.ts (/Users/jakehe/Code/my-new-app/.webpack/main/index.js:12348:27)
    at __webpack_require__ (/Users/jakehe/Code/my-new-app/.webpack/main/index.js:12490:42)
    at /Users/jakehe/Code/my-new-app/.webpack/main/index.js:12561:37
    at Object.<anonymous> (/Users/jakehe/Code/my-new-app/.webpack/main/index.js:12564:12)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
````

**Comment by timfish** [comment]
You'll need to use a relative import to ensure you get the main process code:

```ts
import * as Sentry from "@sentry/electron/main";
```

**Comment by zhex900** [comment]
Thank you!

**Comment by timfish** [comment]
I'm going to try and improve the error messages here because I'm sure this will come up again!
