### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isReady')

### ISSUE THREAD

**Issue by Finn0811** [getsentry/sentry-electron#434]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.4`
- [x] Electron version - `electron@v17.1.0`
- [x] Platform - `Windows`

## Description

After updating to 3.0.4 I see this error when starting my electron app:

```
13:31:07.938 › TypeError: Cannot read properties of undefined (reading 'isReady')
    at electron-normalize.js:16:12
    at Module../node_modules/@sentry/electron/esm/main/electron-normalize.js (electron-normalize.js:23:2)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../node_modules/@sentry/electron/esm/main/context.js (normalize.js:90:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../node_modules/@sentry/electron/esm/main/sdk.js (renderers.js:43:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
```

Even after removing all Sentry.init() calls in main and renderer process, the error still appears. Only downgrading to 2.5.1 fixes the issue.

What additional information do I need to provide?

**Comment by johnwils** [comment]
I'm experiencing this issue myself.

`electron@17.4.0`
`@sentry/electron@v3.0.7`

@Finn0811 did you figure out a fix in the end?
