### ISSUE TITLE
Electron React Boilerplate support out-of-the-box

### ISSUE THREAD

**Issue by jgresham** [getsentry/sentry-electron#445]
A popular starter project for Electron, Electron React Boilerplate (1/5 Github stars as Electron repo), doesn't work with sentry out of the box https://github.com/electron-react-boilerplate/electron-react-boilerplate

In main process, replacing sentry-election with sentry-node, packaging works. So it seems like an issue in sentry-election.

The run-time error using `import * as Sentry from '@sentry/electron/main'`
```
[1] npm run build:renderer exited with code 0
[0] ERROR in ./node_modules/@sentry/electron/preload/index.js
[0] Self-reference dependency has unused export name: This should not happen
[0]  @ ./node_modules/@sentry/electron/main/integrations/preload-injection.js 40:18-59
[0]  @ ./node_modules/@sentry/electron/main/integrations/index.js 13:26-56
[0]  @ ./node_modules/@sentry/electron/main/index.js 7:59-84
[0]  @ ./src/main/main.ts 39:28-60
[0] 
[0] ERROR in ./node_modules/@sentry/electron/preload/legacy.js
[0] Self-reference dependency has unused export name: This should not happen
[0]  @ ./node_modules/@sentry/electron/main/integrations/preload-injection.js 39:18-60
[0]  @ ./node_modules/@sentry/electron/main/integrations/index.js 13:26-56
[0]  @ ./node_modules/@sentry/electron/main/index.js 7:59-84
[0]  @ ./src/main/main.ts 39:28-60
[0] 
[0] webpack compiled with 2 errors
```

The run-time error using `import * as Sentry from '@sentry/electron'`
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: e.require is not a function
    at i (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:97116)
    at t.getIntegrations (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:49966)
    at Object.2549 (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:49159)
    at r (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:888475)
    at Object.5533 (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:592804)
    at r (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:888475)
    at /tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:889145
    at Object.<anonymous> (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:889175)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)

```

**Comment by jgresham** [comment]
> Try this instead:
> 
> ```ts
> // main
> import * as Sentry from '@sentry/electron/dist/main';
> // renderer
> import * as Sentry from '@sentry/electron/dist/renderer';
> ```
Doesn't look like it is exported. Linter also warns of this.
```
[0] ERROR in ./src/main/main.ts 41:28-65
[0] Module not found: Error: Package path ./dist/main is not exported from package /home/johns/dev/NiceNode/node_modules/@sentry/electron (see exports field in /home/johns/dev/NiceNode/node_modules/@sentry/electron/package.json)
```

**Comment by amilajack** [comment]
I should I only tested this on `2.5.4`.

**Comment by jgresham** [comment]
Error with version: `@sentry/electron": "^3.0.5`

Steps to reproduce:
```
# Clone ERB:
git clone --depth=1 \
  https://github.com/electron-react-boilerplate/electron-react-boilerplate \
  your-project-name
cd your-project-name
npm install
npm install @sentry/electron
# Import & Sentry.init() in src/main/main.ts
npm run package
./release/build/ElectronReact-4.5.0.AppImage
```

**Comment by timfish** [comment]
Thanks for opening an issue, I'll take a look!

**Comment by timfish** [comment]
Due to `require.resolve` usage, webpack was erroring on files that it doesn't even include in the bundle. The fix will be in the next release. 

I've added a slimmed down `electron-react-boilerplate` app to our CI tests so this doesn't regress.

In the main process:
https://github.com/getsentry/sentry-electron/blob/136d2c49d4ade2965600840ebd63724523b1f950/examples/electron-react-boilerplate/src/main/main.ts#L15-L22

Note that `debug`, `autoSessionTracking` and `onFatalError` options here are purely for our CI tests.

In the renderer:
https://github.com/getsentry/sentry-electron/blob/136d2c49d4ade2965600840ebd63724523b1f950/examples/electron-react-boilerplate/src/renderer/index.tsx#L3-L5

**Comment by jgresham** [comment]
@timfish amazing! thank you for the quick fix! 
(and Thank you too for debugging help @amilajack and great work on ERB!)
