### ISSUE TITLE
Stack trace files point to localhost instead of source files.

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry-electron#588]
When using the code provided below and `const loadFromFile = false` the events reported in Sentry will have the following stack trace:

```
Error: test event
  at onClick(http://localhost:43288)
  at Object.Be(http://localhost:43288)
  at Ke(http://localhost:43288)
  at <anonymous>(http://localhost:43288)
  at Er(http://localhost:43288)
  at xr(http://localhost:43288)
  at <anonymous>(http://localhost:43288)
  at Ie(http://localhost:43288)
  at <anonymous>(http://localhost:43288)
  at zr(http://localhost:43288)
  at Jt(http://localhost:43288)
  at Gt(http://localhost:43288)
  at t.unstable_runWithPriority(http://localhost:43288)
  at Vl(http://localhost:43288)
  at Me(http://localhost:43288)
  at Yt(http://localhost:43288)
```

While setting the option to true `const loadFromFile = true` the stack trace points to the files, which can be resolved using source maps:

```
Error: test event
  at onClick(app:///build/static/js/main.a6537570.chunk.js:1:530)
  at Object.Be(app:///build/static/js/2.ef71193e.chunk.js:2:23511)
  at Ke(app:///build/static/js/2.ef71193e.chunk.js:2:23665)
  at ? (app:///build/static/js/2.ef71193e.chunk.js:2:41674)
  at Er(app:///build/static/js/2.ef71193e.chunk.js:2:41768)
  at xr(app:///build/static/js/2.ef71193e.chunk.js:2:42183)
  at ? (app:///build/static/js/2.ef71193e.chunk.js:2:47836)
  at Ie(app:///build/static/js/2.ef71193e.chunk.js:2:123879)
  at ? (app:///build/static/js/2.ef71193e.chunk.js:2:43644)
  at zr(app:///build/static/js/2.ef71193e.chunk.js:2:43674)
  at Jt(app:///build/static/js/2.ef71193e.chunk.js:2:31943)
  at Gt(app:///build/static/js/2.ef71193e.chunk.js:2:31169)
  at t.unstable_runWithPriority(app:///build/static/js/2.ef71193e.chunk.js:2:129860)
  at Vl(app:///build/static/js/2.ef71193e.chunk.js:2:52036)
  at Me(app:///build/static/js/2.ef71193e.chunk.js:2:123618)
  at Yt(app:///build/static/js/2.ef71193e.chunk.js:2:30961)
```

It is a current requirement to run the application with `loadFromFile` set to false. Is there a workaround to keep the option to load files from localhost and be able to get meaningful stack traces for events?

## Versions + Platform

- [ ] SDK version - @sentry/electron@v4.1.0
- [ ] Electron version - electron@v20.0.0
- [ ] Platform - Windows and MacOS

## Additional details

One curious point is that, on both cases, there is an warning from the SDK:

```
Sentry Logger [warn]: SentryError: An event processor returned null, will not send event.
    at /../../node_modules/@sentry/core/cjs/baseclient.js:590:17
```

App.js:

```
import React from "react"
export const Sentry = window.require("@sentry/electron")

Sentry.init({ 
  dsn: "",
  debug: true,
});

export default function App() {
  return (
    <body>
      <center>
        <br/>
        <br/>
        <button onClick={() => {
          console.log("About to call Senty.captureException")
          Sentry.captureException(new Error("test event"))
        }}>
          Capture Exception
        </button>
      </center>
    </body>
  )
}
```

main.js:

```
const loadFromFile = false
const { app, BrowserWindow } = require('electron')
const remote = require('@electron/remote/main')
remote.initialize()
const Sentry = require("@sentry/electron")
Sentry.init({ 
  dsn: "",
  release: "sentry-test",
  debug: true
});

let mainWindow, mainContents
let reallyQuit = false
function createWindow(staticServerAddress) {
  mainWindow = new BrowserWindow({
    width: 1400, 
    height: 900,
    minWidth: 750,
    minHeight: 500,
    frame: true,
    backgroundColor: '#1d1d1d',
    title: "electron-sentry-test",
    show: true,
    webPreferences: {
      webviewTag: true,
      webSecurity: false,
      nodeIntegration: true,
      plugins: true,
      contextIsolation: false,      //Required for remote to work
    }
  })
  mainContents = mainWindow.webContents
  mainContents.toggleDevTools()
  remote.enable(mainContents)

  if (loadFromFile) {
    const url = require('url')
    const path = require('path')
    mainWindow.loadURL(
      url.format({
        pathname: path.join(__dirname, 'index.html'),
        protocol: 'file:',
        slashes: true
      })
    )
  } else {
    mainContents.loadURL(staticServerAddress,  {"extraHeaders" : "pragma: no-cache\n"})
  }

  //On Windows, closing the app generate this event.
  mainWindow.on("close", () => {
    if (reallyQuit) {
      mainWindow.destroy()
    }
  })
}

//Simple static file server so we can load the app from localhost: instead of file:, enabling Firebase analytics to work
async function startStaticServer() {

  return new Promise(resolve => {
    const static = require('node-static');
    const http = require('http');
    const fileServer = new static.Server(__dirname);
    const staticServer = http.createServer((req, res) => {
      if (req.url === "/") {
        req.url = "/index.html"
      }
      fileServer.serve(req, res);
    })
    const port = 43288
    staticServer.on("error", err => {
      if (err.code === "EADDRINUSE") {
        //Port is already in use.  We hope that it's another instance of <redacted> and roll with it.
        resolve(`http://localhost:${port}/`)
      } else {
        app.exit("Error creating local static server")
      }
    })
    try {
      staticServer.listen(port, "127.0.0.1", () => {
        resolve(`http://localhost:${port}/`)
      });
    }
    catch (err) {
    }
  })
}

app.on('ready', async () => {
  const staticServerAddress = await startStaticServer()
  createWindow(staticServerAddress)
})

app.on("before-quit", evt => {reallyQuit = true})
app.on("will-quit", () => {app.exit(0)})
app.on("window-all-closed", () => {if (process.platform !== 'darwin') {app.exit(0)}})
```

**Comment by toschlog** [comment]
Hello, @timfish!  I'm glad to see this item logged and tracked.  I'm eager to see it fixed; I hope it's not too complicated a change.

Thanks,

 - Matt

**Comment by timfish** [comment]
Does anyone have a minimal reproduction demonstrating this issue? 

@rbisol did send me a zip of a project but I couldn't get it running.

**Comment by toschlog** [comment]
@timfish I'm the user who reported the issue and created the sample project.  What trouble are you having?

**Comment by timfish** [comment]
I tried `npm run electron` and got the following error with no app displayed:
![image](https://user-images.githubusercontent.com/1150298/206203813-5db21af3-bcbe-4f49-b905-0af1295b8ad2.png)

**Comment by toschlog** [comment]
Instead of using `npm run electron` try this:

1. run "npm run build-electron-dev"
2. cd to dist/win-unpacked
3. Run "Hearo.exe"

Then if that works:

4. Click on the "Capture Exception" button

What OS are you building on?  I may not have includes the files needed to build on Mac.

**Comment by toschlog** [comment]
Hi, @timfish.  Any updates on this?  Anything I can do to help?

**Comment by timfish** [comment]
I couldn't get it to load but I've only got access to a Mac at the moment!

**Comment by toschlog** [comment]
Ah, sorry about that.  Grab the attached file, put it in the root of the project, rename it to "entitlements.mac.plist", and then build with `npm run build-electron-dev`.  You can then run "Hearo" in the dist/mac folder.

I just did this on my Mac and it worked, so I'm keeping my fingers crossed that you'll have success. 

[entitlements.mac.plist.txt](https://github.com/getsentry/sentry-electron/files/10386983/entitlements.mac.plist.txt)

**Comment by timfish** [comment]
> npm run build-electron-dev

With the copy of the repository I was supplied, this fails with:

```
Cannot find module: 'react'. Make sure this package is installed.
```

I've double checked the URL normalisation code and we only modify `file` URLs. I can't see anything the Electron SDK does that could cause the line/column numbers to be lost from a stack trace and [I've added tests to ensure this](https://github.com/getsentry/sentry-electron/pull/626).

If you can supply a public repository with a minimal reproduction of the issue, please re-open this and I'd be happy to take another look.
