### ISSUE TITLE
No matching export in "@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "DEFAULT_ENVIRONMENT"

### ISSUE THREAD

**Issue by lsarrazi** [getsentry/sentry-electron#666]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.4.0

### Electron Version

22.3.3

### What platform are you using?

None

### Steps to Reproduce

1. Setup a project with Vite
2. Install @sentry/electron
3. Build

### Expected Result

Expected to run fine as before with @sentry/electron:4.3.0

### Actual Result

Got this error:

```
X [ERROR] No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "DEFAULT_ENVIRONMENT"

    ../../node_modules/@sentry/browser/esm/profiling/utils.js:1:9:
      1 │ import { DEFAULT_ENVIRONMENT } from '@sentry/core';
        ╵          ~~~~~~~~~~~~~~~~~~~

X [ERROR] No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "addTracingExtensions"

    ../../node_modules/@sentry/browser/esm/index.js:2:108:
      2 │ ...Filters, SDK_VERSION, Scope, addBreadcrumb, addGlobalEventProcessor, addTracingExtensions, captureEvent, captureException, captureMessage, configureScope, cr... 
        ╵                                                                         ~~~~~~~~~~~~~~~~~~~~

X [ERROR] No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "extractTraceparentData"

    ../../node_modules/@sentry/browser/esm/index.js:2:211:
      2 │ ... captureException, captureMessage, configureScope, createTransport, extractTraceparentData, getActiveTransaction, getCurrentHub, getHubFromCarrier, makeMain,... 
        ╵                                                                        ~~~~~~~~~~~~~~~~~~~~~~vite v3.2.5 building for development...


X [ERROR] No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "getActiveTransaction"

    ../../node_modules/@sentry/browser/esm/index.js:2:235:
      2 │ ...ureMessage, configureScope, createTransport, extractTraceparentData, getActiveTransaction, getCurrentHub, getHubFromCarrier, makeMain, setContext, setExtra, ... 
        ╵                                                                         ~~~~~~~~~~~~~~~~~~~~
watching for file changes...


X [ERROR] No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "spanStatusfromHttpCode"

    ../../node_modules/@sentry/browser/esm/index.js:2:360:
      2 │ ...mCarrier, makeMain, setContext, setExtra, setExtras, setTag, setTags, setUser, spanStatusfromHttpCode, startTransaction, trace, withScope } from '@sentry/core'; 
        ╵                                                                                   ~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "trace"

    ../../node_modules/@sentry/browser/esm/index.js:2:402:
      2 │ ...mCarrier, makeMain, setContext, setExtra, setExtras, setTag, setTags, setUser, spanStatusfromHttpCode, startTransaction, trace, withScope } from '@sentry/core'; 
        ╵                                                                                                                             ~~~~~


build started...
C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 6 errors:
../../node_modules/@sentry/browser/esm/index.js:2:108: ERROR: No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "addTracingExtensions"
../../node_modules/@sentry/browser/esm/index.js:2:211: ERROR: No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "extractTraceparentData"
../../node_modules/@sentry/browser/esm/index.js:2:235: ERROR: No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "getActiveTransaction"
../../node_modules/@sentry/browser/esm/index.js:2:360: ERROR: No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "spanStatusfromHttpCode"
../../node_modules/@sentry/browser/esm/index.js:2:402: ERROR: No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "trace"
...
    at failureErrorWithLog (C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:1575:15)
    at C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:1033:28
    at runOnEndCallbacks (C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:1447:61)
    at buildResponseToResult (C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:1031:7)
    at C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:1143:14
    at responseCallbacks.<computed> (C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:680:9)
    at handleIncomingPacket (C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:735:9)
    at Socket.readFromStdout (C:\Users\alpin\Documents\noticia\node_modules\vite\node_modules\esbuild\lib\main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 108,
        file: '../../node_modules/@sentry/browser/esm/index.js',
        length: 20,
        line: 2,
        lineText: "export { FunctionToString, Hub, InboundFilters, SDK_VERSION, Scope, addBreadcrumb, addGlobalEventProcessor, addTracingExtensions, captureEvent, captureException, captureMessage, configureScope, createTransport, extractTraceparentData, getActiveTransaction, getCurrentHub, getHubFromCarrier, makeMain, setContext, setExtra, setExtras, setTag, setTags, setUser, spanStatusfromHttpCode, startTransaction, trace, withScope } from '@sentry/core';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "addTracingExtensions"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 211,
        file: '../../node_modules/@sentry/browser/esm/index.js',
        length: 22,
        line: 2,
        lineText: "export { FunctionToString, Hub, InboundFilters, SDK_VERSION, Scope, addBreadcrumb, addGlobalEventProcessor, addTracingExtensions, captureEvent, captureException, captureMessage, configureScope, createTransport, extractTraceparentData, getActiveTransaction, getCurrentHub, getHubFromCarrier, makeMain, setContext, setExtra, setExtras, setTag, setTags, setUser, spanStatusfromHttpCode, startTransaction, trace, withScope } from '@sentry/core';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "extractTraceparentData"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 235,
        file: '../../node_modules/@sentry/browser/esm/index.js',
        length: 20,
        line: 2,
        lineText: "export { FunctionToString, Hub, InboundFilters, SDK_VERSION, Scope, addBreadcrumb, addGlobalEventProcessor, addTracingExtensions, captureEvent, captureException, captureMessage, configureScope, createTransport, extractTraceparentData, getActiveTransaction, getCurrentHub, getHubFromCarrier, makeMain, setContext, setExtra, setExtras, setTag, setTags, setUser, spanStatusfromHttpCode, startTransaction, trace, withScope } from '@sentry/core';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "getActiveTransaction"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 360,
        file: '../../node_modules/@sentry/browser/esm/index.js',
        length: 22,
        line: 2,
        lineText: "export { FunctionToString, Hub, InboundFilters, SDK_VERSION, Scope, addBreadcrumb, addGlobalEventProcessor, addTracingExtensions, captureEvent, captureException, captureMessage, configureScope, createTransport, extractTraceparentData, getActiveTransaction, getCurrentHub, getHubFromCarrier, makeMain, setContext, setExtra, setExtras, setTag, setTags, setUser, spanStatusfromHttpCode, startTransaction, trace, withScope } from '@sentry/core';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "spanStatusfromHttpCode"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 402,
        file: '../../node_modules/@sentry/browser/esm/index.js',
        length: 5,
        line: 2,
        lineText: "export { FunctionToString, Hub, InboundFilters, SDK_VERSION, Scope, addBreadcrumb, addGlobalEventProcessor, addTracingExtensions, captureEvent, captureException, captureMessage, configureScope, createTransport, extractTraceparentData, getActiveTransaction, getCurrentHub, getHubFromCarrier, makeMain, setContext, setExtra, setExtras, setTag, setTags, setUser, spanStatusfromHttpCode, startTransaction, trace, withScope } from '@sentry/core';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "trace"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 9,
        file: '../../node_modules/@sentry/browser/esm/profiling/utils.js',
        length: 19,
        line: 1,
        lineText: "import { DEFAULT_ENVIRONMENT } from '@sentry/core';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "../../node_modules/@sentry/browser/node_modules/@sentry/core/esm/index.js" for import "DEFAULT_ENVIRONMENT"'
    }
  ],
  warnings: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timfish** [comment]
Do you have any other Sentry dependencies installed? 

`@sentry/electron` v4.4.0 requires other `@sentry/*` dependencies at v7.48.0.

**Comment by timfish** [comment]
I'm just tidying up the stale issues in this repository. Please do reopen this or a new issue if you have a reproduction for this.
