### ISSUE TITLE
use v0.5.5 with webpack failed `TypeError: module.require is not a function`

### ISSUE THREAD

**Issue by ncaq** [getsentry/sentry-electron#92]
relation #81 .

This problem from #84 .

[sentry-electron/dispatch.ts at 326c7a0625f3ae650d390ddd0d667b0da7ea3f99 · getsentry/sentry-electron](https://github.com/getsentry/sentry-electron/blob/326c7a0625f3ae650d390ddd0d667b0da7ea3f99/src/dispatch.ts#L24)
use `module.require`.

But, webpack do not support `module.require`.
[Align module-object to node's module-object · Issue #20 · webpack/webpack](https://github.com/webpack/webpack/issues/20)

So, This is failed, below error message.

~~~
yarn run v1.7.0
$ cross-env NODE_ENV=development electron .
App threw an error during load
TypeError: module.require is not a function
    at new ElectronFrontend (/home/ncaq/Desktop/foo/app/webpack:/node_modules/@sentry/electron/dist/dispatch.js:38:1)
    at Object.initAndBind (/home/ncaq/Desktop/foo/app/webpack:/node_modules/@sentry/core/dist/sdk.js:24:1)
    at init (/home/ncaq/Desktop/foo/app/webpack:/node_modules/@sentry/electron/dist/sdk.js:51:1)
    at Object../src/sentry.js (/home/ncaq/Desktop/foo/app/webpack:/src/sentry.js:3:1)
    at __webpack_require__ (/home/ncaq/Desktop/foo/app/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/home/ncaq/Desktop/foo/app/webpack:/src/main.js:18:1)
    at Object../src/main.js (/home/ncaq/Desktop/foo/app/main.js:64808:30)
    at __webpack_require__ (/home/ncaq/Desktop/foo/app/webpack:/webpack/bootstrap:19:1)
    at /home/ncaq/Desktop/foo/app/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/ncaq/Desktop/foo/app/main.js:87:10)
A JavaScript error occurred in the main process
~~~

I try rewrite `module.require` to dynamic import.
But, `module.require` in constructor, I can not use `await`.

I think that should split init to `mainInit` and `rendererInit`.
To solve dependend statically.

**Comment by ncaq** [comment]
@jan-auer notify

**Comment by Anenth** [comment]
@ncaq Have you found a solution for this?

**Comment by hatton** [comment]
FWIW this only happens to me when I run the packaged the app (i.e., the asar), not when I just run it from code. I removed the sentry initialization from the main process, leaving just the render process hooked to sentry for now.

Using webpack 4, sentry/electron 0.12.1, typescript{"target": "es6", "moduleResolution": "node",     "module": "commonjs"}

**Comment by Superjo149** [comment]
Having the same issues with sentry-electron@0.13.0 & electron@3.0.0

**Comment by Superjo149** [comment]
Latest working version for me is 0.11.0

**Comment by morajabi** [comment]
I temporarily, excluded compiling of `@sentry/electron` in my `webpack.config.js`, here's the quick fix:
```javascript
// webpack.config.js
module.exports = {
 // ... 
 externals: [
    { '@sentry/electron': `require('@sentry/electron')` },
  ],
  // ...
}
```

**Comment by HazAT** [comment]
I just released `0.15.0`; could you guys try the following, if you have this issue instead of importing and using `init` like:
```
import * as Sentry from '@sentry/electron'
Sentry.init({...});
```

Use `init` on the main process with a deep import like:

```
import { init } from '@sentry/electron/dist/main'
import * as Sentry from '@sentry/electron'
init({...});
```

If this works I will write this into the docs.

**Comment by kairon-v** [comment]
I just updated to the `0.15.0` and I`m receiving the following exception:

```
Uncaught TypeError: Cannot read property 'getAppPath' of undefined
    at Object../node_modules/@sentry/electron/dist/main/normalize.js (renderer.dev.js:19327)
    at __webpack_require__ (renderer.dev.js:726)
    at fn (renderer.dev.js:103)
    at Object../node_modules/@sentry/electron/dist/main/backend.js (renderer.dev.js:18483)
    at __webpack_require__ (renderer.dev.js:726)
    at fn (renderer.dev.js:103)
    at Object../node_modules/@sentry/electron/dist/main/client.js (renderer.dev.js:18754)
    at __webpack_require__ (renderer.dev.js:726)
    at fn (renderer.dev.js:103)
    at Object../node_modules/@sentry/electron/dist/main/index.js (renderer.dev.js:19123)
```
Importing like

```
import { init } from '@sentry/electron/dist/main';

init({
    dsn: 'my dsn',
    enableNative: false
});
```

**Comment by iwnnay** [comment]
I don't think that would have solved my issue either. It was actually that the app didn't have Sentry installed on it and, for some reason, including it in the externals wasn't enough for the dynamicRequire method that Sentry is running.

I was able to circumvent this issue by installing Sentry into both the Electron app and the contained app.

The same thing worked when packaging the example app in this repository.

You could test out your code change there, electron-builder is the easiest to implement.

**Comment by Norbz** [comment]
> I just released `0.15.0`; could you guys try the following, if you have this issue instead of importing and using `init` like:
> 
> ```
> import * as Sentry from '@sentry/electron'
> Sentry.init({...});
> ```
> Use `init` on the main process with a deep import like:
> 
> ```
> import { init } from '@sentry/electron/dist/main'
> import * as Sentry from '@sentry/electron'
> init({...});
> ```
> If this works I will write this into the docs.

Tried this. Not getting the 'require is not a function' error anymor but getting this warning during compilation : 
```
WARNING  Compiled with 1 warnings                                                                                                 
warning  in ./node_modules/encoding/lib/iconv-loader.js
Critical dependency: the request of a dependency is an expression
```

Doesn't prevent the app to start or work... but I'm not getting any error in sentry project though.

Here is my test :
```
import { init } from '@sentry/electron/dist/main';

init({
    dsn: XXX,
});

setTimout(process.crash, 20000);
```

Using Electron 3 and sentry/electron 0.15.0

**Comment by dperetti** [comment]
Still the same issue with @sentry/electron 0.17.3

**Comment by fshafiee** [comment]
> I just updated to the `0.15.0` and I`m receiving the following exception:
> 
> ```
> Uncaught TypeError: Cannot read property 'getAppPath' of undefined
>     at Object../node_modules/@sentry/electron/dist/main/normalize.js (renderer.dev.js:19327)
>     at __webpack_require__ (renderer.dev.js:726)
>     at fn (renderer.dev.js:103)
>     at Object../node_modules/@sentry/electron/dist/main/backend.js (renderer.dev.js:18483)
>     at __webpack_require__ (renderer.dev.js:726)
>     at fn (renderer.dev.js:103)
>     at Object../node_modules/@sentry/electron/dist/main/client.js (renderer.dev.js:18754)
>     at __webpack_require__ (renderer.dev.js:726)
>     at fn (renderer.dev.js:103)
>     at Object../node_modules/@sentry/electron/dist/main/index.js (renderer.dev.js:19123)
> ```
> 
> Importing like
> 
> ```
> import { init } from '@sentry/electron/dist/main';
> 
> init({
>     dsn: 'my dsn',
>     enableNative: false
> });
> ```

@dperetti, I ran into the same problem. Apparently, it is  a problem with deep import in the renderer process. 
Importing `init` from the root module in the renderer process should fix the issue.

In renderer process:

```js
import * as Sentry from '@sentry/electron/'

Sentry.init({})
```

In main process:

```js
import { init } from '@sentry/electron/dist/main'

init({})
```

**Comment by kasenvr** [comment]
> 
> 
> I just released `0.15.0`; could you guys try the following, if you have this issue instead of importing and using `init` like:
> 
> ```
> import * as Sentry from '@sentry/electron'
> Sentry.init({...});
> ```
> 
> Use `init` on the main process with a deep import like:
> 
> ```
> import { init } from '@sentry/electron/dist/main'
> import * as Sentry from '@sentry/electron'
> init({...});
> ```
> 
> If this works I will write this into the docs.

This got it to remove the error for me, please do update the docs.

**Comment by timfish** [comment]
This issue was fixed quite a while ago by using both the `main` and `browser` field in package.json so Webpack picks the correct code paths. Feel free to open new issues if problems persist!

**Comment by jgresham** [comment]
A popular starter project for Electron doesn't work with sentry out of the box https://github.com/electron-react-boilerplate/electron-react-boilerplate

If anyone knows what needs fixed from their side, please let me know or open a PR to them perhaps. If I find out, I'll open a PR.

**Comment by jgresham** [comment]
In main process, replacing sentry-election with sentry-node, packaging works. So it seems like an issue in sentry-election.

The run-time error using `import * as Sentry from '@sentry/electron/main'`
```
[1] npm run build:renderer exited with code 0
[0] ERROR in ./node_modules/@sentry/electron/preload/index.js
[0] Self-reference dependency has unused export name: This should not happen
[0]  @ ./node_modules/@sentry/electron/main/integrations/preload-injection.js 40:18-59
[0]  @ ./node_modules/@sentry/electron/main/integrations/index.js 13:26-56
[0]  @ ./node_modules/@sentry/electron/main/index.js 7:59-84
[0]  @ ./src/main/main.ts 39:28-60
[0] 
[0] ERROR in ./node_modules/@sentry/electron/preload/legacy.js
[0] Self-reference dependency has unused export name: This should not happen
[0]  @ ./node_modules/@sentry/electron/main/integrations/preload-injection.js 39:18-60
[0]  @ ./node_modules/@sentry/electron/main/integrations/index.js 13:26-56
[0]  @ ./node_modules/@sentry/electron/main/index.js 7:59-84
[0]  @ ./src/main/main.ts 39:28-60
[0] 
[0] webpack compiled with 2 errors
```

The run-time error using `import * as Sentry from '@sentry/electron'`
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: e.require is not a function
    at i (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:97116)
    at t.getIntegrations (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:49966)
    at Object.2549 (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:49159)
    at r (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:888475)
    at Object.5533 (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:592804)
    at r (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:888475)
    at /tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:889145
    at Object.<anonymous> (/tmp/.mount_NiceNoWXQ3Jr/resources/app.asar/dist/main/main.js:2:889175)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)

```

**Comment by zarkin404** [comment]
just use:
```
const Sentry = require('@sentry/electron/dist/main')
Sentry.init({...})
```

**Comment by timfish** [comment]
@zarkin404 What's wrong with the currently documented way?
```ts
const Sentry = require('@sentry/electron/main');
// or
import * as Sentry from '@sentry/electron/main';
```
