### ISSUE TITLE
ENOENT, file not found on captureException

### ISSUE THREAD

**Issue by sk91** [getsentry/sentry-electron#94]
Hi,
I am trying to integrate sentry-electron with my electron project using electron-builder and electron-weback.

when using `captureException(new Error('sentry test')` the following error occures:

```
 Error: ENOENT, webpack:/src/main/main.js not found in /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:114:19)
    at Object.fs.readFile (ELECTRON_ASAR.js:483:16)
    at /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/utils/src/fs.ts:17:5
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/utils/src/fs.ts:16:10)
    at step (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/utils/fs.js:32:23)
    at Object.next (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/utils/fs.js:13:53)
    at /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/utils/fs.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/utils/fs.js:3:12)
    at Object.readFileAsync (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/utils/fs.js:49:12)
    at /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/src/parsers.ts:96:29
    at step (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:32:23)
    at Object.next (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:13:53)
    at /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:3:12)
    at /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/src/parsers.ts:95:33
    at Array.map (<anonymous>)
    at /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/src/parsers.ts:95:15
    at step (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:32:23)
    at Object.next (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:13:53)
    at /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:3:12)
    at readSourceFiles (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:112:12)
    at /Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/src/parsers.ts:167:29
    at step (/Users/maximk/projects/selfkey/Identity-Wallet/dist/mac/SelfKey Identity Wallet.app/Contents/Resources/app.asar/node_modules/@sentry/node/dist/parsers.js:32:23) code: 'ENOENT', errno: -2 }
```

in dev ( non asar file) all works well.
what might be the issue here ?

```
"electron-builder": "^20.19.2",
 "electron-webpack": "^2.1.2",
"@sentry/electron": "0.7.0",
 "electron": "^2.0.4",
```

**Comment by sk91** [comment]
it does not fail on v0.5.4, although adds a note in on the console:

```
There was 1 error encountered while processing this event

Source code was not found for app:///webpack:/src/main/main.js
```

**Comment by HazAT** [comment]
I will take a look at this, thanks for reporting.

**Comment by HazAT** [comment]
Hey, I wasn't able to reproduce this locally.
If you could provide a minimal reproducible case I will be happy to debug it.

**Comment by alxmiron** [comment]
Have same issue with v0.8.0. Regardless is it dev o production, I get:
```
{ Error: ENOENT: no such file or directory, open '/Users/mac/dev/hitask-web/dist/desktop-dev/webpack:/packages/desktop/src/main/main.js'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/mac/dev/hitask-web/dist/desktop-dev/webpack:/packages/desktop/src/main/main.js' }
```

when catch an error in main.js:
```
try {
  throw new Error('test error')
} catch (error) {
  Sentry.captureException(error)
}
```

I use webpack to compile `/Users/mac/dev/hitask-web/packages/desktop/src/main/main.js` to `/Users/mac/dev/hitask-web/dist/desktop-dev/main.js`. I suppose the error is related to webpack

**Comment by mitchheddles** [comment]
I had a similar issue and managed to get it working by disabling the `webpack.devtool`, setting it to `hidden-source-maps` also worked.

After a bit of digging I was able to pin the error to the `readSourceFiles` method inside the @sentry/node package.
A try/catch around `readFileAsync` in [parsers.ts](https://github.com/getsentry/raven-js/blob/master/packages/node/src/parsers.ts#L89) could avoid this error bubbling up. Having said that, I'm not sure if this is the real issue, but rather a Webpack thing.

**Comment by mitchheddles** [comment]
@chevonc I'm having the same problem. I followed the @sentry/electron [sourcemaps docs](https://docs.sentry.io/clients/electron/sourcemaps/), as well as the  @sentry/node [ones](https://docs.sentry.io/clients/node/sourcemaps/), but still couldn't get it working.

In my case, my main process is bundled into one file, `main.prod.js` with sourcemap `main.prod.js.map`.

I've tried both `webpack.devtool: hidden-source-maps` and `webpack.devtool: source-maps` + removing `main.prod.js.map` and the reference from `main.prod.js` before packaging the app.

Both of these options prevented the `ENOENT, file not found on captureException` error, but any errors in sentry, from the main process, don't pickup the sourcemap.

As per the node implementation documentation, I did try using the `dataCallback` (`beforeSend` in the electron SDK) to rename the files in the stacktrace, but couldn't get any combination to work, `~/`, `app:///`, `/`, etc.

**Comment by chevonc** [comment]
Man, why's this so hard. I got the sentry `/example` app in this repro working but it's using an outdated version of the electron SDK. I'll try updating to `0.8.0` and see if it works as expected still

**Comment by mitchheddles** [comment]
@hazAT is there any more information on how sentry resolves source maps? Given an error from a file with the url `app:///main.prod.js` Should the artifact `~/main.prod.js` match?

Do you think this is just an error with node sourcemaps?

**Comment by chevonc** [comment]
Upgraded to latest `0.8.1` and still hitting this error

```
[15:29:08.305] [info] { '0': Error: Interval Test Error
    at Timeout._onTimeout (/Volumes/Data/code/guilded/client/www/electron/build/webpack:/electron/ElectronApp.js:114:33)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) }
{ Error: ENOENT: no such file or directory, open '/Volumes/Data/code/guilded/client/www/electron/build/webpack:/electron/ElectronApp.js'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Volumes/Data/code/guilded/client/www/electron/build/webpack:/electron/ElectronApp.js' }```

**Comment by chevonc** [comment]
Ping on this and how to get sourcemaps working correctly for webpack minified, compiled bundle? Any ideas
