### ISSUE TITLE
Example can't run

### ISSUE THREAD

**Issue by BlackHole1** [getsentry/sentry-electron#97]
Hello, I am trying to run the code in example and find it unable to run.

Error Info:
```
A JavaScript error occurred in the main process
Uncaught Exception:
SentryError: Invalid DSN
    at new SentryError (/Users/black-hole/Code/github/sentry-electron/example/node_modules/@sentry/core/dist/error.js:18:28)
    at DSN.fromString (/Users/black-hole/Code/github/sentry-electron/example/node_modules/@sentry/core/dist/dsn.js:64:19)
    at new DSN (/Users/black-hole/Code/github/sentry-electron/example/node_modules/@sentry/core/dist/dsn.js:37:18)
    at new FrontendBase (/Users/black-hole/Code/github/sentry-electron/example/node_modules/@sentry/core/dist/base.js:124:24)
    at new MainFrontend (/Users/black-hole/Code/github/sentry-electron/example/node_modules/@sentry/electron/dist/main/frontend.js:27:9)
    at new ElectronFrontend (/Users/black-hole/Code/github/sentry-electron/example/node_modules/@sentry/electron/dist/dispatch.js:41:22)
    at Object.initAndBind (/Users/black-hole/Code/github/sentry-electron/example/node_modules/@sentry/core/dist/sdk.js:24:20)
    at init (/Users/black-hole/Code/github/sentry-electron/example/node_modules/@sentry/electron/dist/sdk.js:51:12)
    at Object.<anonymous> (/Users/black-hole/Code/github/sentry-electron/example/sentry.js:3:1)
    at Object.<anonymous> (/Users/black-hole/Code/github/sentry-electron/example/sentry.js:8:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/black-hole/Code/github/sentry-electron/example/main.js:10:1)
    at Object.<anonymous> (/Users/black-hole/Code/github/sentry-electron/example/main.js:46:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/Users/black-hole/Code/github/sentry-electron/example/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/Users/black-hole/Code/github/sentry-electron/example/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (/Users/black-hole/Code/github/sentry-electron/example/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:365:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```

System Info:
```
OS: MAC
Node Version: v10.5.0
yarn Version: 1.7.0
sentry-electron Version: 0.7
```

history command:
```shell
# example git:(master) yarn
yarn install v1.7.0
(node:3080) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 98.88s.
# example git:(master) yarn build
yarn run v1.7.0
$ webpack -p
Hash: 36056a36779bb206afa0
Version: webpack 4.8.3
Time: 3992ms
Built at: 2018-07-18 09:52:06
        Asset       Size  Chunks             Chunk Names
    bundle.js   66.8 KiB       0  [emitted]  main
bundle.js.map    289 KiB       0  [emitted]  main
   index.html   1.23 KiB          [emitted]
    style.css  982 bytes          [emitted]
   sentry.png   8.41 KiB          [emitted]
  pattern.png   8.94 KiB          [emitted]
Entrypoint main = bundle.js bundle.js.map
 [2] external "electron" 42 bytes {0} [built]
 [4] (webpack)/buildin/global.js 509 bytes {0} [built]
[25] (webpack)/buildin/module.js 519 bytes {0} [built]
[27] ./sentry.js 119 bytes {0} [built]
[28] ./app/index.js 633 bytes {0} [built]
[29] multi ./app/index.js 28 bytes {0} [built]
    + 24 hidden modules
✨  Done in 5.61s.
#  example git:(master) yarn start
yarn run v1.7.0
$ electron .
App threw an error during load
SentryError: Invalid DSN
// Error Info
```

I don't know what happened. I hope you can answer it. 
Thank you very much.

**Comment by BlackHole1** [comment]
Sorry. I think I've found the problem. It should be the problem that I didn't configure DSN. I'm going to try it
